/**
 * sync-index.js — Decision Index Auto-Sync
 *
 * Scans ALL session logs in Agent/decision-logs/ and rebuilds
 * decision-index.md with exactly one summary line per real session.
 *
 * This tool is the backbone of the auto-index feature. It is called
 * automatically by: `new`, `close`, `sync`, and `status` commands.
 * It can also be run directly: node sync-index.js
 *
 * Skips files marked as "EXAMPLE SESSION LOG" so template examples
 * never pollute the real decision history.
 *
 * Output format per entry:
 *   * **Session N:** [Domain] | Path: <chosen> | Status: ACTIVE | [`decision-logs/session-N.md`]
 *
 * Usage: node sync-index.js (or via .\a-mem sync)
 * Dependencies: None (pure Node.js)
 *
 * @author Aayan
 * @license MIT
 */

const fs = require('fs');
const path = require('path');

const agentDir  = path.resolve(__dirname, '..');
const logsDir   = path.join(agentDir, 'decision-logs');
const indexPath = path.join(agentDir, 'decision-index.md');

/**
 * Reads all decision logs, extracts a 1-line summary for each real session,
 * and writes the result to decision-index.md.
 *
 * @returns {number} number of sessions indexed (excluding examples)
 */
function syncIndex() {
  // ── Collect and sort log files numerically ───────────────────────────
  let logs;
  try {
    logs = fs.readdirSync(logsDir)
      .filter(f => f.endsWith('.md'))
      .sort((a, b) => {
        const na = parseInt((a.match(/\d+/) || ['0'])[0], 10);
        const nb = parseInt((b.match(/\d+/) || ['0'])[0], 10);
        return na - nb;
      });
  } catch (e) {
    // decision-logs dir doesn't exist yet — nothing to sync
    return 0;
  }

  // ── Extract 1-line summary from each non-example log ─────────────────
  const entries = [];
  for (const file of logs) {
    try {
      const content = fs.readFileSync(path.join(logsDir, file), 'utf-8');

      // Skip template example files
      if (content.includes('THIS IS AN EXAMPLE SESSION LOG')) continue;

      const sessionNum  = (file.match(/\d+/) || ['?'])[0];
      const titleMatch  = content.match(/^#\s*Session\s*\d+[:\s–-]*(.+)/m);
      const domainMatch = content.match(/\*\*Domain:\*\*\s*([^\n<]+)/);
      const statusMatch = content.match(/\*\*Status:\*\*\s*(ACTIVE|REVOKED|SUPERSEDED)/i);
      const chosenMatch = content.match(/\*\*Chosen Path:\*\*\s*([^\n<]+)/);

      const title  = titleMatch  ? titleMatch[1].trim()  : file;
      const domain = domainMatch ? domainMatch[1].trim() : 'Unknown';
      const status = statusMatch ? statusMatch[1].trim() : 'ACTIVE';
      const chosen = chosenMatch ? chosenMatch[1].trim() : 'See log';

      entries.push(
        `* **Session ${sessionNum}:** [${domain}] | Path: ${chosen} | Status: ${status} | [\`decision-logs/${file}\`]`
      );
    } catch (e) { /* skip unreadable log */ }
  }

  // ── Rebuild decision-index.md ─────────────────────────────────────────
  const header = [
    '# Decision Index (Summary Pointers)',
    '<!-- ',
    '  PURPOSE: A compact, pointer-only index of all decisions ever made.',
    '  This file is AUTO-GENERATED by .\\a-mem sync — do not edit manually.',
    '  Full details are in the linked log files.',
    '  ',
    '  FORMAT: * **Session #:** [Domain] | Path: <chosen> | Status: <status> | [`decision-logs/session-#.md`]',
    '-->',
    '',
    '<!-- Auto-synced by .\\a-mem sync -->',
    '',
  ].join('\n');

  const body = entries.length > 0
    ? entries.join('\n') + '\n'
    : '<!-- No sessions logged yet. Run .\\a-mem new "title" to start your first session. -->\n';

  fs.writeFileSync(indexPath, header + body);
  return entries.length;
}

// ── Run directly ──────────────────────────────────────────────────────────
if (require.main === module) {
  const count = syncIndex();
  console.log('=== DECISION INDEX SYNC ===');
  console.log(`✅ Index updated — ${count} real session(s) indexed.`);
}

module.exports = { syncIndex };
